template = "https://github.com/giellalt/template-lang-und"
rev_id = 253
template_sha = "5e69b0634aa0bd9773dece52e5b15d3003d605f1"

[replacements]
__GLOTTOLOG_ID__ = "taga1272"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-bgs"
__UND2C__ = "bgs"
__UNDEFINED__ = "Tagabawa"
__UND__ = "bgs"
